### PR TITLE
[DO-596] Text breaking in next/prev buttons

### LINKED ISSUE #46: Next/previous card - word goes through the borders
**Describe the bug**
If word is wider than previous/next card, it goes through the borders

**To Reproduce**
1. Go to 'https://exactpro.github.io/docs-toolkit/features/'
2. Make viewport's width 790px
3. Scroll down to next/prev cards

**Expected behavior**
All words are inside borders.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by StanG4313**
Closes #46 

Problem seems to be fixed, but wider code blocks make our buttons look not so good. I believe, it will work fine after fixing issue with wide code blocks

### CODE REVIEW

File: components/ep/layout/SurroundDocCard.vue [hunk 1]
```diff
@@ -33,6 +33,7 @@ defineProps<{
   <NuxtLink
     :to="withTrailingSlash(doc._path ?? '')"
     class="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700"
+    style="word-wrap: break-word word-break: keep-all"
```
Comment (d0rich) [inline components/ep/layout/SurroundDocCard.vue:36]: You should separate properties in style tag with `;`. I guess these rules are not applied.
```suggestion
    style="word-wrap: break-word; word-break: keep-all"
```

Anyway, inline styles is not a good practice. It is better to use some classes from tailwind (https://tailwindcss.com/docs/word-break) or create class specifically for this card.

**Review by d0rich — CHANGES_REQUESTED** [review]
Problem still exists

File: components/ep/layout/SurroundDocCard.vue (hunk 1 above)
Comment (StanG4313) [reply components/ep/layout/SurroundDocCard.vue]: image
With `;` added it works
Will check if I can use tailwind class as you requested

**Review by d0rich — APPROVED** [review]
